package main

import "fmt"

func findKthSmallest(coins []int, k int) int64 {
	// Remove redundant coins.
	// If d divides c, then every multiple of c is already
	// generated by d.
	filtered := make([]int, 0, len(coins))

	for _, c := range coins {
		redundant := false

		for _, d := range coins {
			if d != c && c%d == 0 {
				redundant = true
				break
			}
		}

		if !redundant {
			filtered = append(filtered, c)
		}
	}

	coins = filtered
	n := len(coins)

	// Greatest common divisor.
	gcd := func(a, b int64) int64 {
		for b != 0 {
			a, b = b, a%b
		}
		return a
	}

	// Least common multiple.
	// Returns limit+1 if the result would exceed limit.
	lcm := func(a, b, limit int64) int64 {
		g := gcd(a, b)
		a /= g

		if a > limit/b {
			return limit + 1
		}

		return a * b
	}

	// Count how many distinct positive integers <= x
	// are divisible by at least one coin.
	count := func(x int64) int64 {
		var total int64

		for mask := 1; mask < (1 << n); mask++ {
			var multiple int64 = 1
			bits := 0
			valid := true

			for i := 0; i < n; i++ {
				if mask&(1<<i) != 0 {
					bits++

					multiple = lcm(
						multiple,
						int64(coins[i]),
						x,
					)

					if multiple > x {
						valid = false
						break
					}
				}
			}

			if !valid {
				continue
			}

			cnt := x / multiple

			// Inclusion-exclusion:
			// odd number of coins -> add
			// even number of coins -> subtract
			if bits%2 == 1 {
				total += cnt
			} else {
				total -= cnt
			}
		}

		return total
	}

	// Upper bound:
	// k multiples of the smallest coin are always possible.
	minCoin := int64(coins[0])

	for _, c := range coins {
		if int64(c) < minCoin {
			minCoin = int64(c)
		}
	}

	lo := int64(1)
	hi := minCoin * int64(k)

	// Binary search for the smallest x
	// such that at least k amounts <= x exist.
	for lo < hi {
		mid := lo + (hi-lo)/2

		if count(mid) >= int64(k) {
			hi = mid
		} else {
			lo = mid + 1
		}
	}

	return lo
}

func main() {
	// Example 1
	coins1 := []int{3, 6, 9}
	k1 := 3

	fmt.Println(findKthSmallest(coins1, k1))
	// Output: 9

	// Example 2
	coins2 := []int{5, 2}
	k2 := 7

	fmt.Println(findKthSmallest(coins2, k2))
	// Output: 12
}